/// <reference types="cypress" />

describe('Tic Tac toe', () => {
  it('Assures that the index page has been loaded correctly', () => {
    cy.visit('/')
    cy.get('[data-cy=main-title]').should('exist').and('be.visible')
    cy.get('[data-cy=main-title]').should('contain.text', 'Tic Tac Toe')
    cy.get('[data-cy=span-choose-side').should('exist').and('be.visible')
    cy.get('[data-cy=span-choose-side').should('contain.text', 'Choose a side:')
    cy.get('[data-cy=start-game-button-x] > div').should('have.class', 'i-tabler-x')
    cy.get('[data-cy=start-game-button-circle] > div').should('have.class', 'i-tabler-circle')
    cy.get('[data-cy=game-grid]').should('not.exist')
  })
  it('Start game on X side and wins', () => {
    cy.get('[data-cy=start-game-button-x]').click()
    cy.get('[data-cy=start-game-modal]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-1]').click()
    cy.get('[data-cy=grid-tile-1] > [data-cy=x-tile-icon]').should('exist')
    cy.get('[data-cy=grid-tile-1] > [data-cy=circle-tile-icon]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('not.exist')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('exist')
    cy.get('[data-cy=grid-tile-2]').click()
    cy.get('[data-cy=grid-tile-2] > [data-cy=x-tile-icon]').should('not.exist')
    cy.get('[data-cy=grid-tile-2] > [data-cy=circle-tile-icon]').should('exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-4]').click()
    cy.get('[data-cy=grid-tile-4] > [data-cy=x-tile-icon]').should('exist')
    cy.get('[data-cy=grid-tile-4] > [data-cy=circle-tile-icon]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('not.exist')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('exist')
    cy.get('[data-cy=grid-tile-5]').click()
    cy.get('[data-cy=grid-tile-5] > [data-cy=x-tile-icon]').should('not.exist')
    cy.get('[data-cy=grid-tile-5] > [data-cy=circle-tile-icon]').should('exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-7]').click()
  })
  it('Check correct X winner and restarts game', () => {
    cy.get('[data-cy=game-interface]').should('not.exist')
    cy.get('[data-cy=end-game-modal]').should('exist').and('be.visible')
    cy.get('[data-cy=end-game-text]').should('contain.text', 'The winner of the game is: ')
    cy.get('[data-cy=x-endgame-icon]').should('exist').and('be.visible')
    cy.get('[data-cy=circle-endgame-icon]').should('not.exist')
    cy.get('[data-cy=restart-game-button]').should('exist').and('be.visible')
    cy.get('[data-cy=restart-game-button]').should('contain.text', 'Restart game')
    cy.get('[data-cy=restart-game-button]').click()
    cy.get('[data-cy=end-game-interface]').should('not.exist')
    cy.get('[data-cy=game-interface]').should('not.exist')
    cy.get('[data-cy=game-grid]').should('not.exist')
  })
  it('Start game in circle side and wins', () => {
    cy.get('[data-cy=start-game-button-circle]').click()
    cy.get('[data-cy=start-game-modal]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-1]').click()
    cy.get('[data-cy=grid-tile-1] > [data-cy=x-tile-icon]').should('not.exist')
    cy.get('[data-cy=grid-tile-1] > [data-cy=circle-tile-icon]').should('exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-2]').click()
    cy.get('[data-cy=grid-tile-2] > [data-cy=x-tile-icon]').should('exist')
    cy.get('[data-cy=grid-tile-2] > [data-cy=circle-tile-icon]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('not.exist')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('exist')
    cy.get('[data-cy=grid-tile-5]').click()
    cy.get('[data-cy=grid-tile-5] > [data-cy=x-tile-icon]').should('not.exist')
    cy.get('[data-cy=grid-tile-5] > [data-cy=circle-tile-icon]').should('exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('exist').and('be.visible')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('not.exist')
    cy.get('[data-cy=grid-tile-3]').click()
    cy.get('[data-cy=grid-tile-3] > [data-cy=x-tile-icon]').should('exist')
    cy.get('[data-cy=grid-tile-3] > [data-cy=circle-tile-icon]').should('not.exist')
    cy.get('[data-cy=turn-displayer]').should('contain.text', 'Turn: ')
    cy.get('[data-cy=turn-displayer] > [data-cy=x-turn-display]').should('not.exist')
    cy.get('[data-cy=turn-displayer] > [data-cy=circle-turn-display]').should('exist')
    cy.get('[data-cy=grid-tile-9]').click()
  })
  it('Check correct circle winner', () => {
    cy.get('[data-cy=game-interface]').should('not.exist')
    cy.get('[data-cy=end-game-modal]').should('exist').and('be.visible')
    cy.get('[data-cy=end-game-text]').should('contain.text', 'The winner of the game is: ')
    cy.get('[data-cy=circle-endgame-icon]').should('exist').and('be.visible')
    cy.get('[data-cy=x-endgame-icon]').should('not.exist')
    cy.get('[data-cy=restart-game-button]').should('exist').and('be.visible')
    cy.get('[data-cy=restart-game-button]').should('contain.text', 'Restart game')
    cy.get('[data-cy=restart-game-button]').click()
    cy.get('[data-cy=end-game-interface]').should('not.exist')
    cy.get('[data-cy=game-interface]').should('not.exist')
    cy.get('[data-cy=game-grid]').should('not.exist')
  })
})
